// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuaGqRWyxVvyJ6XqZg8XVFANg3ZOReyb4',
    appId: '1:553598930930:web:c7b639f50ac86cd495a56b',
    messagingSenderId: '553598930930',
    projectId: 'exercise5a-c9577',
    authDomain: 'exercise5a-c9577.firebaseapp.com',
    storageBucket: 'exercise5a-c9577.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ILxkzc3pu4Hn-Zc7bXHZyN4nrvF-qM8',
    appId: '1:553598930930:android:c6ecf77048fcde6c95a56b',
    messagingSenderId: '553598930930',
    projectId: 'exercise5a-c9577',
    storageBucket: 'exercise5a-c9577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMxK62r2DTncYF9-E5G3hNyT03e4Z81vk',
    appId: '1:553598930930:ios:2219bc0f0922621595a56b',
    messagingSenderId: '553598930930',
    projectId: 'exercise5a-c9577',
    storageBucket: 'exercise5a-c9577.firebasestorage.app',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMxK62r2DTncYF9-E5G3hNyT03e4Z81vk',
    appId: '1:553598930930:ios:2219bc0f0922621595a56b',
    messagingSenderId: '553598930930',
    projectId: 'exercise5a-c9577',
    storageBucket: 'exercise5a-c9577.firebasestorage.app',
    iosBundleId: 'com.example.exercise5a',
  );
}
